{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xiaojinzi.component",
    "module": "component-plugin",
    "version": "2.0.0-beta8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "component-plugin-2.0.0-beta8.jar",
          "url": "component-plugin-2.0.0-beta8.jar",
          "size": 25196,
          "sha512": "012cb48cb97700c423ff33b1cedad26c05351dcb361ec6d68d83e0cecd16615820d34f22f0e3a7bdda362bbad66721ea9824219b5e54344fa3b5c5dc80db5afd",
          "sha256": "adcb3a87b1d035bb7cec5a6ce138363435410d859893504fe246d357befc7577",
          "sha1": "49bfb097a5e7e80d74963c7ed13ef0861d9d32d7",
          "md5": "dcc5a3cbfe103ae275e02af7327d9ec8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-all",
          "version": {
            "requires": "5.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "component-plugin-2.0.0-beta8.jar",
          "url": "component-plugin-2.0.0-beta8.jar",
          "size": 25196,
          "sha512": "012cb48cb97700c423ff33b1cedad26c05351dcb361ec6d68d83e0cecd16615820d34f22f0e3a7bdda362bbad66721ea9824219b5e54344fa3b5c5dc80db5afd",
          "sha256": "adcb3a87b1d035bb7cec5a6ce138363435410d859893504fe246d357befc7577",
          "sha1": "49bfb097a5e7e80d74963c7ed13ef0861d9d32d7",
          "md5": "dcc5a3cbfe103ae275e02af7327d9ec8"
        }
      ]
    }
  ]
}
