{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xiaojinzi.component",
    "module": "component-plugin",
    "version": "2.0.0-beta11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "component-plugin-2.0.0-beta11.jar",
          "url": "component-plugin-2.0.0-beta11.jar",
          "size": 25196,
          "sha512": "26382f8fca5feba0edd1b076015526b544899ef988ea31c5549562c98e8986e95c49af2208d3c26695928be4b36f7c8aca6acfb5a6b125ea46c38f7081952f37",
          "sha256": "76f91b92d212a3cd48d8c4db32dc43bad45676051687600104a4d0271d3616dc",
          "sha1": "fa8b2a20564d2f41509219d29752b96a82b4c764",
          "md5": "895ee7189341a1ae75c2bfe3580d56dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-all",
          "version": {
            "requires": "5.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "component-plugin-2.0.0-beta11.jar",
          "url": "component-plugin-2.0.0-beta11.jar",
          "size": 25196,
          "sha512": "26382f8fca5feba0edd1b076015526b544899ef988ea31c5549562c98e8986e95c49af2208d3c26695928be4b36f7c8aca6acfb5a6b125ea46c38f7081952f37",
          "sha256": "76f91b92d212a3cd48d8c4db32dc43bad45676051687600104a4d0271d3616dc",
          "sha1": "fa8b2a20564d2f41509219d29752b96a82b4c764",
          "md5": "895ee7189341a1ae75c2bfe3580d56dd"
        }
      ]
    }
  ]
}
