{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xiaojinzi.component",
    "module": "component-plugin",
    "version": "2.0.0-beta7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "component-plugin-2.0.0-beta7.jar",
          "url": "component-plugin-2.0.0-beta7.jar",
          "size": 25136,
          "sha512": "195468a8c309d132de51cc1cbd2805c16805dc015e82018a6e8081b3d33f4542531a5f1e4ae09da923ec98ebd232e30503f0f2213464bc20633143284957ffc8",
          "sha256": "b140a0acf588bb7ed90e5e268d4de31e23feb0f604539ff0a2a0e076813ea645",
          "sha1": "cfaa12ecb47931affbb3fb256766f3d7d98e6512",
          "md5": "e5e9e20b679863fee5a164bee01308aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-all",
          "version": {
            "requires": "5.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "component-plugin-2.0.0-beta7.jar",
          "url": "component-plugin-2.0.0-beta7.jar",
          "size": 25136,
          "sha512": "195468a8c309d132de51cc1cbd2805c16805dc015e82018a6e8081b3d33f4542531a5f1e4ae09da923ec98ebd232e30503f0f2213464bc20633143284957ffc8",
          "sha256": "b140a0acf588bb7ed90e5e268d4de31e23feb0f604539ff0a2a0e076813ea645",
          "sha1": "cfaa12ecb47931affbb3fb256766f3d7d98e6512",
          "md5": "e5e9e20b679863fee5a164bee01308aa"
        }
      ]
    }
  ]
}
